### ISSUE TITLE
to_euler failing with some quaternions

### ISSUE THREAD

**Issue by klarh** [glotzerlab/rowan#17]
It looks like `to_euler` may be failing in some cases with particularly clean orientations; I'd guess that some tolerances may need to be added to the calculation, at a glance. For example,

```rowan.to_euler((-.5, .5, -.5, .5), convention='xyz', axis_type='intrinsic')```

produces the following rotation matrix inside the function:

```
array([[ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.]])
```

which causes both sets of arguments for `arctan2` to compute `alpha` and `gamma` to be (0, 0), causing the resulting set of angles to be `(0, pi/2, 0)`.

**Comment by vyasr** [comment]
This problem arises because in any choice of convention or axis only `beta` is solvable independent of the others. All other terms will be multiplied by either `cos(beta)` or `sin(beta)`, and when that term is zero, the simplest terms that can be used to solve for `alpha` and `gamma` don't work anymore because they're all identically zero. This issue can be fixed by checking for the corresponding 0 values and branching accordingly to instead using the more complicated matrix components that instead involve the other trig function in `beta` (i.e. if `sin(beta) == 0`, only use terms containing `cos(beta)`).
